myprofile/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView

urlpatterns = patterns('MyJobs.myprofile.views',
    url(r'^$', RedirectView.as_view(url='/profile/view/')),
    url(r'^view$', 'edit_profile', name='view_profile'),
    url(r'^view/$', 'edit_profile', name='view_profile'),
    url(r'^view/delete$', 'delete_item', name='delete_item'),
    url(r'^view/edit$', 'handle_form', name='handle_form'),
    url(r'^view/details$', 'get_details', name='get_details'),
    url(r'^export/profile.csv$', 'to_csv', name='to_csv'),
)

urls.py
from django.conf.urls import *
from django.contrib import admin

from tastypie.api import Api

from myjobs.api import UserResource, SavedSearchResource

admin.autodiscover()

# API Resources
v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(SavedSearchResource())

handler500 = "myjobs.views.error_500"


urlpatterns = patterns('',
    url('', include('MyJobs.myjobs.urls')),
    url(r'^candidates/',
        include('MyJobs.mydashboard.urls')),
    url(r'^accounts/', include('MyJobs.registration.urls')),
    url(r'^profile/',
        include('MyJobs.myprofile.urls')),
    url(r'^saved-search/',
        include('MyJobs.mysearches.urls')),
    url(r'^api/', include(v1_api.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^authorize/', include('MyJobs.mysignon.urls')),
    url(r'^message/', include('MyJobs.mymessages.urls')),
)

myprofile/models.py
import datetime

from django.core.validators import ValidationError

from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from collections import OrderedDict

from registration import signals as reg_signals
from registration.models import ActivationProfile
from myjobs.models import User


class ProfileUnits(models.Model):
    """
    This is the parent class for all user information. Creating any new
    profile unit instances (Education, Name, Email etc) end up in the
    ProfileUnits queryset as well.
    
    """
    date_created = models.DateTimeField(default=datetime.datetime.now,
                                        editable=False)
    date_updated = models.DateTimeField(default=datetime.datetime.now,
                                        editable=False)
    content_type = models.ForeignKey(ContentType, editable=False, null=True)
    user = models.ForeignKey(User, editable=False)

    def save(self, *args, **kwargs):
        """
        Custom save method to set the content type of the instance.
        
        """
        if not self.content_type:
            self.content_type = ContentType.objects.get_for_model(self.__class__)
        super(ProfileUnits, self).save(*args, **kwargs)

    def get_fields(self):
        """
        Returns the module type, value, and field type for all
        fields on a specific model
        """
        field_list = []
        for field in self._meta.local_fields:
            if not field.primary_key:
                field_list.append([field.verbose_name.title(),
                                   self.__getattribute__(field.name),
                                   field.get_internal_type()])
        return field_list

    def __unicode__(self):
        return self.content_type.name

    def get_model_name(self):
        return self.content_type.model

    @classmethod
    def get_verbose_class(object):
        return object.__name__

    def get_verbose(self):
        return self.content_type.name.title()


class Name(ProfileUnits):
    given_name = models.CharField(max_length=30,
                                  verbose_name=_("first name"))
    family_name = models.CharField(max_length=30,
                                   verbose_name=_("last name"))
    primary = models.BooleanField(default=False,
                                  verbose_name=_("Is primary name?"))

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """

        full_name = '%s %s' % (self.given_name, self.family_name)
        return full_name.strip()

    def save(self, *args, **kwargs):
        """
        Custom name save method to ensure only one name object per user
        has one primary=True. We avoid a race condition by locking the transaction
        using select_for_update.
        """
        duplicate_names = Name.objects.filter(user=self.user,
                                              given_name=self.given_name,
                                              family_name=self.family_name)
        if duplicate_names:
            if self.primary:
                if self.id in [name.id for name in duplicate_names]:
                    self.switch_primary_name()
                else:
                    duplicate = duplicate_names[0]
                    if duplicate.primary is False:
                        try:
                            current_primary = Name.objects.select_for_update().get(
                                primary=True, user=self.user)
                        except Name.DoesNotExist:
                            duplicate.primary = True
                            duplicate.save()
                        else:
                            current_primary.primary = False
                            current_primary.save()
                            duplicate.primary = True
                            duplicate.save()
            elif self.id in [name.id for name in duplicate_names]:
                super(Name, self).save(*args, **kwargs)
        else:
            if self.primary:
                self.switch_primary_name()
            else:
                super(Name, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.get_full_name()

    def switch_primary_name(self, *args, **kwargs):
        try:
            temp = Name.objects.select_for_update().get(primary=True,
                                                        user=self.user)
        except Name.DoesNotExist:
            super(Name, self).save(*args, **kwargs)
        else:
            temp.primary = False
            temp.save()
            super(Name, self).save(*args, **kwargs)


def save_primary(sender, instance, created, **kwargs):
    user = instance.user
    if len(Name.objects.filter(user=user)) == 1 and created:
        try:
            user.profileunits_set.get(content_type__name="name",
                                          name__primary=True)
        except ProfileUnits.DoesNotExist:
            instance.primary = True
            instance.save()


post_save.connect(save_primary, sender=Name, dispatch_uid="save_primary")


class Education(ProfileUnits):
    EDUCATION_LEVEL_CHOICES = (
        ('', _('Education Level')),
        (3, _('High School')),
        (4, _('Non-Degree Education')),
        (5, _('Associate')),
        (6, _('Bachelor')),
        (7, _('Master')),
        (8, _('Doctoral')),
    )
    organization_name = models.CharField(max_length=255,
                                         verbose_name=_('institution'))
    degree_date = models.DateField(verbose_name=_('completion date'))
    city_name = models.CharField(max_length=255, blank=True, null=True,
                                 verbose_name=_('city'))
    # ISO 3166-2:2007
    country_sub_division_code = models.CharField(max_length=5, blank=True,
                                                 verbose_name=_("State/Region")) 
    country_code = models.CharField(max_length=3, blank=True,
                                    verbose_name=_("country"))  # ISO 3166-1
    # ISCED-2011 Can be [0-8]
    education_level_code = models.IntegerField(choices=EDUCATION_LEVEL_CHOICES,
                                               verbose_name=_("education level"))
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    education_score = models.CharField(max_length=255, blank=True, null=True,
                                       verbose_name=_("GPA"))
    degree_name = models.CharField(max_length=255, blank=True, null=True,
                                   verbose_name=_('degree type'))
    degree_major = models.CharField(max_length=255, verbose_name=_('major'))
    degree_minor = models.CharField(max_length=255, blank=True, null=True,
                                    verbose_name=_('minor'))


class Address(ProfileUnits):
    label = models.CharField(max_length=60, blank=True,
                             verbose_name=_('Address Label'))
    address_line_one = models.CharField(max_length=255, blank=True,
                                        verbose_name=_('Address Line One'))
    address_line_two = models.CharField(max_length=255, blank=True,
                                        verbose_name=_('Address Line Two'))
    city_name = models.CharField(max_length=255, blank=True,
                                 verbose_name=_("City"))
    country_sub_division_code = models.CharField(max_length=5, blank=True,
                                                 verbose_name=_("State/Region"))
    country_code = models.CharField(max_length=3, blank=True, 
                                    verbose_name=_("Country"))
    postal_code = models.CharField(max_length=12, blank=True,
                                   verbose_name=_("Postal Code"))


class Telephone(ProfileUnits):
    USE_CODE_CHOICES = (
        ('', 'Phone Type'),
        ('Home', 'Home'),
        ('Work', 'Work'),
        ('Mobile', 'Mobile'),
        ('Pager', 'Pager'),
        ('Fax', 'Fax'),
        ('Other', 'Other')
    )
    channel_code = models.CharField(max_length=30, editable=False, blank=True)
    country_dialing = models.CharField(max_length=3, blank=True,
                                       verbose_name=_("Country Code"))
    area_dialing = models.CharField(max_length=5, blank=True,
                                    verbose_name=_("Area Code")) 
    number = models.CharField(max_length=10, blank=True,
                              verbose_name=_("Local Number"))
    extension = models.CharField(max_length=5, blank=True)
    use_code = models.CharField(max_length=30, choices=USE_CODE_CHOICES,
                                blank=True, verbose_name=_("Phone Type"))

    def save(self, *args, **kwargs):
        if self.use_code == "Home" or self.use_code == "Work" or self.use_code == "Other":
            self.channel_code = "Telephone"
        if self.use_code == "Mobile":
            self.channel_code = "MobileTelephone"
        if self.use_code == "Pager":
            self.channel_code = "Pager"
        if self.use_code == "Fax":
            self.channel_code = "Fax"
        super(Telephone, self).save(*args, **kwargs)


class EmploymentHistory(ProfileUnits):
    position_title = models.CharField(max_length=255,
                                      verbose_name=_("Position Title"))
    organization_name = models.CharField(max_length=255, blank=True,
                                         verbose_name=_("Company"))
    start_date = models.DateField(verbose_name=_("Start Date"))
    current_indicator = models.BooleanField(default=False,
                                            verbose_name=_("I still work here"))

    # Optional fields
    end_date = models.DateField(blank=True, null=True)

templates/myprofile/modules/address.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.label }}</b>
            </td>
            <td>
                {{ item.address_line_one }}

                {% if item.address_line_two %}

                {{ item.address_line_two }}

                {% endif %}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/education.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{item.get_education_level_code_display}} - {{item.degree_major}}</b>
                <br>
                {{ item.organization_name }}
            </td>
            <td>
                {{ item.degree_date }}
            </td>
            <td class="action">
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/employmenthistory.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.position_title}}</b>
                <br>
                {{ item.organization_name }}
            </td>
            <td>
                {% if item.current_indicator == True %}

                {{item.start_date}} - Present

                {%else%}

                {{item.start_date}} - {{item.end_date}}

                {%endif%}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/license.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.license_name }}</b>
            </td>
            <td>
                {{ item.license_type }}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/militaryservice.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.country_code }}</b>
            </td>
            <td>
                {{ item.branch }} - {{ item.department }}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/name.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.given_name }} {{ item.family_name }}</b>
            </td>
            <td>
                {% if not item.primary %}

                Not Primary

                {% else %}

                Primary

                {% endif %}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/secondaryemail.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.email }}</b>
            </td>
            <td>
                {% if item.verified %}
                Verified
                {% else %}
                Not Verified
                {% endif %}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/summary.html
{% load i18n %}
<b>{{ module.0.headline }}</b>
<div class="clear"></div>
<div>{{ module.0.the_summary }}</div>
<div class="clear"></div>
<a class="btn-link pull-right sum-edit" href="{% url 'handle_form' %}?id={{ module.0.id }}&module={{ module.0.get_verbose.title }}">{% trans 'Edit' %}</a>

templates/myprofile/modules/telephone.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.use_code }}</b>
            </td>
            <td>
                {# One liner because django likes to add spaces if there are more than one line. #}
                {% if item.country_dialing %}{{ item.country_dialing }}-{% endif %}{% if item.area_dialing %}{{ item.area_dialing }}-{% endif %}{{ item.number }}

                {% if item.extension %}

                Ext. {{ item.extension }}

                {% endif %}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/volunteerhistory.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name}}-{{item.id}}-item">
            <td>
                <b>{{ item.position_title}}</b>
                <br>
                {{ item.organization_name }}
            </td>
            <td>
                {% if item.current_indicator == True %}

                {{item.start_date}} - Present

                {%else%}

                {{item.start_date}} - {{item.end_date}}

                {%endif%}
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/myprofile/modules/website.html
{% load i18n %}
<table class="table table-bordered table-striped small-margin">
    {% for item in module %}
        <tr id="{{item.get_model_name }}-{{item.id }}-item">
            <td>
                <b>{{ item.display_text }}</b>
            </td>
            <td>
                <a href="{{ item.uri }}" target="_blank">{{ item.uri }}</a>
            </td>
            <td class='action'>
                <a class="btn-link" href="{% url 'get_details' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Details' %}</a>
                <a class="btn-link" href="{% url 'handle_form' %}?id={{ item.id }}&module={{ item.get_verbose.title }}">{% trans 'Edit' %}</a>
            </td>
        </tr>
    {% endfor %}
</table>